import {
  Baby,
  Bath,
  BriefcaseMedical,
  Crown,
  Droplets,
  Eye,
  Flower2,
  Gem,
  Gift,
  Grid2X2,
  Hand,
  Heart,
  Package,
  Palette,
  Scissors,
  Shirt,
  ShoppingBag,
  Smile,
  Sparkles,
  SprayCan,
  Sun,
  UserRound,
  WandSparkles,
} from "lucide-react";

const icons = {
  perfume: SprayCan,
  bath: Bath,
  makeup: WandSparkles,
  hair: Scissors,
  face: Smile,
  eyes: Eye,
  skincare: Hand,
  hydration: Droplets,
  sun: Sun,
  baby: Baby,
  men: UserRound,
  fashion: Shirt,
  jewelry: Gem,
  flower: Flower2,
  palette: Palette,
  sparkles: Sparkles,
  favorites: Heart,
  smile: Smile,
  lipstick: Sparkles,
  gift: Gift,
  package: Package,
  shopping: ShoppingBag,
  premium: Crown,
  health: BriefcaseMedical,
  grid: Grid2X2,
};
export function CategoryIcon({ name }: { name: string }) {
  const Icon = icons[name as keyof typeof icons] || Grid2X2;
  return <Icon size={19} />;
}
